import {expect,it} from 'vitest';
import {baseLevel,mergeSwap} from '../fixtures/base';
import {loadCampaignLevel} from '../../../src/campaign/engine/load';
import {createContext} from '../../../src/campaign/engine/context';
import {campaignModules} from '../../../src/campaign/mechanics/registry';
import {parseCampaignState} from '../../../src/campaign/schema';
import {transition} from '../../../src/campaign/engine/turn';
export function currentLevel(){const l=baseLevel();l.id=276;l.chapter=6;l.geometry.routes=[{id:'current',loop:true,cells:[{r:2,c:0},{r:2,c:1},{r:3,c:1},{r:3,c:0}]}];l.mechanics=[{id:'currents',routeIds:['current']}];return l;}
const module=()=>campaignModules.find(m=>m.id==='currents')!;
it('validates disjoint orthogonal authoring with explicit current issues instead of module-availability failures',()=>{
 const l=currentLevel(),route=l.geometry.routes[0]!;
 route.loop=false;expect(module().validate(l)).toContainEqual(expect.objectContaining({code:'current-lane',entityId:'current',message:expect.stringContaining('closed orthogonal')}));route.loop=true;
 l.geometry.routes.push({...route,id:'overlap'});l.mechanics=[{id:'currents',routeIds:['current','overlap']}];expect(module().validate(l)).toContainEqual(expect.objectContaining({code:'current-lane',entityId:'overlap',message:expect.stringContaining('disjoint')}));
 l.geometry.routes.pop();l.mechanics=[{id:'currents',routeIds:['current']}];l.fixtures=[{id:'comet',kind:'comet',at:{r:1,c:0},cells:[{r:1,c:0},{r:2,c:0}],hp:1}];expect(module().validate(l)).toContainEqual(expect.objectContaining({code:'current-lane',entityId:'current',message:expect.stringContaining('fixed stations')}));
});
it('lets an independent disjoint two-cell lane proceed while another cycle waits, in stable route-ID order',()=>{
 const l=currentLevel();l.geometry.routes.push({id:'a-current',loop:true,cells:[{r:0,c:2},{r:0,c:3}]});l.mechanics=[{id:'currents',routeIds:['current','a-current']}];
 const c=createContext(loadCampaignLevel(l));c.state.fixtures.push({id:'ice',kind:'ice',at:{r:2,c:0},hp:1});const old=c.state.pieces.filter(p=>p.at.r>=2).map(p=>structuredClone(p));module().environment!(c);
 expect(c.state.pieces.find(p=>p.id==='piece-0-2')!.at).toEqual({r:0,c:3});expect(c.state.pieces.filter(p=>p.at.r>=2)).toEqual(old);expect(c.state.crew[0]!.at).toEqual({r:3,c:0});expect(c.events.filter(e=>e.type==='current').map(e=>[e.routeId,e.phase])).toEqual([['a-current','shifted'],['current','waiting']]);expect(c.state.mechanics).toContainEqual({id:'currents',shiftCount:1});
});
it('registers the current environment hook after actors rather than transfer',()=>{expect(module()?.environment).toBeTypeOf('function');expect(module()?.transfer).toBeUndefined();});
it('rotates all stable IDs and the last-to-first rider simultaneously, without overwrite',()=>{const c=createContext(loadCampaignLevel(currentLevel())),route=c.state.geometry.routes[0]!,before=route.cells.map(at=>c.state.pieces.find(p=>p.at.r===at.r&&p.at.c===at.c)!.id);module().environment!(c);for(const [i,id]of before.entries())expect(c.state.pieces.find(p=>p.id===id)!.at).toEqual(route.cells[(i+1)%4]);expect(c.state.crew[0]!.at).toEqual(route.cells[0]);expect(new Set(c.events.filter(e=>e.type==='move').map(e=>e.timingGroup)).size).toBe(1);expect(c.state.mechanics).toContainEqual({id:'currents',shiftCount:1});expect(parseCampaignState(JSON.parse(JSON.stringify(c.state)))).toEqual(c.state);});
it.each(['station','ice','actor-rider','actor-pod'] as const)('waits the whole cycle atomically at dynamic %s blockage',kind=>{const c=createContext(loadCampaignLevel(currentLevel())),p=c.state.pieces.find(p=>p.at.r===2&&p.at.c===1)!;if(kind==='station')Object.assign(p,{kind:'station',facing:'left'});if(kind==='ice')c.state.fixtures.push({id:'ice',kind:'ice',at:{r:2,c:1},hp:1});if(kind.startsWith('actor'))c.state.actors.push({id:'whale',kind:'moonwhale',at:{r:2,c:0},routeId:'current',routeIndex:0,passengerIds:[],landing:{r:1,c:0},transferRequested:false});if(kind==='actor-pod'){c.state.crew=[];Object.assign(c.state.pieces.find(p=>p.at.r===3&&p.at.c===0)!,{kind:'pod',passengerIds:[]});}const before=structuredClone(c.state);module().environment!(c);expect(c.state).toEqual(before);expect(c.events.filter(e=>e.type==='move')).toEqual([]);});
it('moves pod passengers and keeps actor riders on the actor above passing empty terrain',()=>{const c=createContext(loadCampaignLevel(currentLevel()));c.state.crew[0]!.carrierId='piece-3-0';Object.assign(c.state.pieces.find(p=>p.id==='piece-3-0')!,{kind:'pod',passengerIds:['crew']});c.state.actors.push({id:'whale',kind:'moonwhale',at:{r:3,c:1},routeId:'current',routeIndex:2,passengerIds:['rider'],landing:{r:2,c:2},transferRequested:false});c.state.crew.push({id:'rider',at:{r:3,c:1},status:'active',carrierId:'whale',rescueMoves:null,shelterMoves:null,shelterStarted:false,vipId:null});module().environment!(c);expect(c.state.crew[0]!.at).toEqual({r:2,c:0});expect(c.state.crew[1]!.at).toEqual({r:3,c:1});expect(c.state.pieces.find(p=>p.id==='piece-2-1')!.at).toEqual({r:3,c:1});});
it('ticks once through the kernel and never on rejection or boosters',()=>{const s=loadCampaignLevel(currentLevel()),r=transition(s,mergeSwap);expect(r.accepted).toBe(true);expect(r.state.mechanics).toContainEqual({id:'currents',shiftCount:1});const bad=transition(s,{type:'swap',from:{r:0,c:0},to:{r:3,c:3}});expect(bad.state).toBe(s);const boost=transition(s,{type:'booster',kind:'demo',at:{r:0,c:3}});expect(boost.accepted).toBe(true);expect(boost.state.mechanics).toEqual(s.mechanics);});
it.each(['open','singleton','jump','overlap','station','comet-footprint'] as const)('rejects invalid authored %s lanes',kind=>{const l=currentLevel(),r=l.geometry.routes[0]!;if(kind==='open')r.loop=false;if(kind==='singleton')r.cells=[r.cells[0]!];if(kind==='jump')r.cells=[{r:0,c:0},{r:2,c:0}];if(kind==='overlap'){l.geometry.routes.push({...r,id:'other'});l.mechanics=[{id:'currents',routeIds:['current','other']}];}if(kind==='station')l.pieces=l.pieces.map(p=>p.id==='piece-2-0'?{id:p.id,at:p.at,kind:'station',facing:'left'}:p);if(kind==='comet-footprint'){l.fixtures=[{id:'comet',kind:'comet',at:{r:1,c:0},cells:[{r:1,c:0},{r:2,c:0}],hp:1}];l.mechanics.push({id:'comets',fixtureIds:['comet']});}expect(()=>loadCampaignLevel(l)).toThrow(/Current|current/);});
