import {describe,expect,it} from 'vitest';
import type {CampaignEvent,CampaignLevel,CampaignState,MechanicId,TurnContext} from '../../../src/campaign/types';
import {campaignModules,initialRuntime} from '../../../src/campaign/mechanics/registry';
import {createContext} from '../../../src/campaign/engine/context';
import {canMoveActor,moveActor} from '../../../src/campaign/engine/transport';
import {parseCampaignLevel,parseCampaignState} from '../../../src/campaign/schema';
import {fallPieces} from '../../../src/campaign/engine/settle';
import {refillPieces} from '../../../src/campaign/engine/settle';

function board(id:MechanicId):CampaignLevel {
 const cells=Array.from({length:4},(_,r)=>Array.from({length:5},(_,c)=>({r,c}))).flat();
 return {id:1000,chapter:20,campaignVersion:'2026.1',rulesVersion:'campaign-1',seed:7,
  geometry:{rows:4,cols:5,mask:Array.from({length:4},()=>Array(5).fill(true)),inactiveCells:[],chambers:[{id:'room',cells,directions:['down']}],gravitySegments:cells.map(p=>({id:`fall-${p.r}-${p.c}`,cells:[p],direction:'down',chamberId:'room'})),refillSources:cells.map(p=>({id:`source-${p.r}-${p.c}`,at:p,segmentId:`fall-${p.r}-${p.c}`})),routes:[],connections:[],endpoints:[]},
  pieces:cells.map(p=>({id:`tile-${p.r}-${p.c}`,kind:'tile',tier:(1+(p.r+p.c)%2) as 1|2,at:p})),crew:[],actors:[],fixtures:[],arrivals:[],mechanics:[],goals:[],moveLimit:null,needMoves:30,presentationId:id,lessonId:null,rewardId:id,metadata:{shapeFamily:'wide-shelf',difficulty:'teaching',purposeTags:[id],assistedAllowance:0,capOverride:null}};
}
function draft(level:CampaignLevel):TurnContext {
 return createContext({level,levelId:level.id,campaignVersion:level.campaignVersion,rulesVersion:level.rulesVersion,turn:1,nextEntityId:1,rngState:7,geometry:structuredClone(level.geometry),pieces:structuredClone(level.pieces),crew:structuredClone(level.crew),actors:structuredClone(level.actors),fixtures:structuredClone(level.fixtures),arrivals:[],mechanics:level.mechanics.map(m=>initialRuntime(m.id)),goalProgress:level.goals.map(g=>({goalId:g.id,completedIds:[]})),movesRemaining:null,points:0,status:'playing',transportedThisTurn:[],pendingTransfers:[]});
}
function module(id:MechanicId){const found=campaignModules.find(m=>m.id===id);expect(found,`${id} must have actual behavior`).toBeDefined();return found!;}
function merge(id:string,cells=[{r:0,c:1},{r:1,c:1},{r:2,c:1}]):Extract<CampaignEvent,{type:'merge'}>{return {type:'merge',sequenceId:0,timingGroup:0,mergeId:id,pieceIds:cells.map((_,i)=>`p-${i}`),cells,at:cells[0]!,before:1,after:2};}
function person(id:string,at:{r:number;c:number},carrierId:string|null){return {id,at,carrierId,status:'active' as const,rescueMoves:null,shelterMoves:null,shelterStarted:false,vipId:null};}
function relayBoard(){const l=board('relays');l.geometry.endpoints=[{id:'home',kind:'station',at:{r:3,c:4},active:false}];l.fixtures=[{id:'relay-1',kind:'relay',at:{r:1,c:0},order:1,active:false,endpointId:'home'},{id:'relay-2',kind:'relay',at:{r:1,c:4},order:2,active:false,endpointId:'home'}];l.mechanics=[{id:'relays',fixtureIds:['relay-1','relay-2']}];l.goals=[{id:'restore',type:'restoreInfrastructure',eligible:{type:'ids',ids:['relay-1','relay-2']}}];return l;}
function magnetBoard(){const l=board('magnets');l.geometry.routes=[{id:'winch-path',cells:[{r:0,c:0},{r:0,c:1},{r:0,c:2}],loop:false}];l.geometry.endpoints=[{id:'dock',kind:'supply-dock',at:{r:0,c:2},active:true}];l.fixtures=[{id:'coil',kind:'magnet',at:{r:1,c:1},routeId:'winch-path',cargoId:'supply',dockId:'dock'}];l.pieces=l.pieces.filter(p=>p.at.r!==0||p.at.c!==0);l.pieces.push({id:'supply',kind:'cargo',cargoKind:'capsule',at:{r:0,c:0},destinationId:'dock',passengerIds:[]});l.mechanics=[{id:'magnets',fixtureIds:['coil']}];l.goals=[{id:'supplies',type:'recoverSupplies',eligible:{type:'ids',ids:['supply']}}];return l;}
function tetherBoard(){const l=board('tethers');l.actors=[{id:'pair',kind:'tether',at:{r:1,c:1},offset:{r:0,c:1},passengerIds:['first','second'],released:false}];l.crew=[person('first',{r:1,c:1},'pair'),person('second',{r:1,c:2},'pair')];l.mechanics=[{id:'tethers',actorIds:['pair']}];l.goals=[{id:'release',type:'transferCreatures',eligible:{type:'ids',ids:['first','second']}}];return l;}
function repairBoard(){const l=board('repair');l.geometry.routes=[{id:'track',cells:[{r:3,c:0},{r:3,c:1},{r:3,c:2}],loop:false}];l.geometry.inactiveCells=[{r:3,c:3}];l.pieces=l.pieces.filter(p=>!(p.at.r===3&&p.at.c===3)&&!(p.at.r===2&&p.at.c===0));l.pieces.push({id:'kit',kind:'cargo',cargoKind:'kit',at:{r:2,c:0},destinationId:'bot',passengerIds:[]});l.actors=[{id:'bot',kind:'repair',at:{r:3,c:0},routeId:'track',routeIndex:0,jobs:[{id:'job',cell:{r:3,c:3}}],nextJob:0,kitId:null}];l.mechanics=[{id:'repair',actorIds:['bot']}];l.goals=[{id:'restore',type:'restoreInfrastructure',eligible:{type:'ids',ids:['job']}}];return l;}
function rendezvousBoard(){const l=board('rendezvous');l.geometry.endpoints=[{id:'pad-a',kind:'staging',at:{r:3,c:1},active:true},{id:'pad-b',kind:'staging',at:{r:3,c:3},active:true}];l.pieces=l.pieces.filter(p=>p.at.r!==3||![1,3].includes(p.at.c));l.pieces.push({id:'pod-a',kind:'pod',at:{r:3,c:1},passengerIds:['first']},{id:'pod-b',kind:'pod',at:{r:3,c:3},passengerIds:['second']});l.crew=[person('first',{r:3,c:1},'pod-a'),person('second',{r:3,c:3},'pod-b')];l.mechanics=[{id:'rendezvous',endpointIds:['pad-a','pad-b'],passengerIds:['first','second']}];l.goals=[{id:'depart',type:'simultaneousDepartures',eligible:{type:'ids',ids:['first','second']}}];return l;}

describe('ordered signal relays',()=>{
 it('ignores a later node and credits each distinct next-node match once',()=>{const m=module('relays'),ctx=draft(relayBoard());m.onMerge!(ctx,merge('late',[{r:0,c:3},{r:1,c:3},{r:2,c:3}]));expect(ctx.state.mechanics[0]).toMatchObject({nextNode:1});m.onMerge!(ctx,merge('one'));m.onMerge!(ctx,merge('one'));expect(ctx.state.mechanics[0]).toMatchObject({nextNode:2});expect(ctx.state.geometry.endpoints[0]!.active).toBe(false);m.onMerge!(ctx,merge('two',[{r:0,c:3},{r:1,c:3},{r:2,c:3}]));expect(ctx.state.geometry.endpoints[0]!.active).toBe(true);expect(ctx.state.goalProgress[0]!.completedIds).toEqual(['relay-1','relay-2']);expect(parseCampaignState(ctx.state)).toEqual(ctx.state);});
 it('rejects order gaps, already active nodes and forged activation saves',()=>{module('relays');const l=relayBoard();(l.fixtures[1] as any).order=3;expect(()=>parseCampaignLevel(l)).toThrow(/relay/);const ctx=draft(relayBoard());(ctx.state.fixtures[0] as any).active=true;expect(()=>parseCampaignState(ctx.state)).toThrow(/relay/);});
});
describe('magnetic supply winches',()=>{
 it('holds supply cargo on its authored winch lane while ordinary gravity clears below it',()=>{module('magnets');const ctx=draft(magnetBoard());ctx.state.geometry.gravitySegments=ctx.state.geometry.gravitySegments.filter(s=>s.cells[0]!.c!==0);ctx.state.geometry.gravitySegments.push({id:'cargo-column',cells:[0,1,2,3].map(r=>({r,c:0})),direction:'down',chamberId:'room'});ctx.state.pieces=ctx.state.pieces.filter(p=>p.at.c!==0||p.id==='supply');fallPieces(ctx);expect(ctx.state.pieces.find(p=>p.id==='supply')!.at).toEqual({r:0,c:0});});
 it('waits on a full destination, pulls only its exact cargo into cleared terrain, then delivers',()=>{const m=module('magnets'),ctx=draft(magnetBoard());m.onMerge!(ctx,merge('full'));expect(ctx.state.pieces.find(p=>p.id==='supply')!.at).toEqual({r:0,c:0});ctx.state.pieces=ctx.state.pieces.filter(p=>p.at.r!==0||p.at.c!==1);m.onMerge!(ctx,merge('clear'));m.onMerge!(ctx,merge('clear'));expect(ctx.state.pieces.find(p=>p.id==='supply')!.at).toEqual({r:0,c:1});ctx.state.pieces=ctx.state.pieces.filter(p=>p.at.r!==0||p.at.c!==2);m.onMerge!(ctx,merge('next'));expect(ctx.state.pieces.some(p=>p.id==='supply')).toBe(false);expect(ctx.state.goalProgress[0]!.completedIds).toEqual(['supply']);expect(parseCampaignState(ctx.state)).toEqual(ctx.state);});
 it('refuses an occupied, blocked or inactive pull target',()=>{const m=module('magnets');for(const obstacle of ['crew','actor','fixture','inactive']){const ctx=draft(magnetBoard());ctx.state.pieces=ctx.state.pieces.filter(p=>p.at.r!==0||p.at.c!==1);if(obstacle==='crew')ctx.state.crew.push(person('visitor',{r:0,c:1},null));if(obstacle==='actor')ctx.state.actors.push({id:'visitor',kind:'pup',at:{r:0,c:1},nurseryId:'n'});if(obstacle==='fixture')ctx.state.fixtures.push({id:'ice',kind:'ice',at:{r:0,c:1},hp:1});if(obstacle==='inactive')ctx.state.geometry.inactiveCells.push({r:0,c:1});m.onMerge!(ctx,merge(obstacle));expect(ctx.state.pieces.find(p=>p.id==='supply')!.at).toEqual({r:0,c:0});}});
 it('rejects duplicate cargo owners, disconnected routes and a forged delivery ledger',()=>{module('magnets');const l=magnetBoard();l.geometry.routes[0]!.cells[1]={r:2,c:2};expect(()=>parseCampaignLevel(l)).toThrow(/magnet/);const duplicated=magnetBoard();duplicated.fixtures.push({...duplicated.fixtures[0]!,id:'second-coil',at:{r:2,c:2}});duplicated.mechanics=[{id:'magnets',fixtureIds:['coil','second-coil']}];expect(()=>parseCampaignLevel(duplicated)).toThrow(/one winch owner/);const ctx=draft(magnetBoard());(ctx.state.mechanics[0] as any).deliveredIds=['supply'];expect(()=>parseCampaignState(ctx.state)).toThrow(/magnet/);});
});
describe('tethered rescue pairs',()=>{
 it('moves both crew with a rigid offset and releases only when both tiles are safe',()=>{const m=module('tethers'),ctx=draft(tetherBoard());expect(moveActor(ctx,'pair',{r:2,c:1})).toBe(true);expect(ctx.state.crew.map(c=>c.at)).toEqual([{r:2,c:1},{r:2,c:2}]);(ctx.state.pieces.find(p=>p.at.r===2&&p.at.c===1) as any).tier=4;expect(m.settle!(ctx)).toBe(false);(ctx.state.pieces.find(p=>p.at.r===2&&p.at.c===2) as any).tier=5;expect(m.settle!(ctx)).toBe(true);expect(ctx.state.actors).toEqual([]);expect(ctx.state.crew.every(c=>c.carrierId===null)).toBe(true);expect(ctx.state.goalProgress[0]!.completedIds).toEqual(['first','second']);expect(m.settle!(ctx)).toBe(false);expect(parseCampaignState(ctx.state)).toEqual(ctx.state);});
 it('checks both footprint cells and preserves blocked pair positions',()=>{module('tethers');for(const obstacle of ['gap','station','crew','fixture']){const ctx=draft(tetherBoard());if(obstacle==='gap')ctx.state.geometry.mask[2]![2]=false;if(obstacle==='station'){const p=ctx.state.pieces.findIndex(p=>p.at.r===2&&p.at.c===2);ctx.state.pieces[p]={id:'station',kind:'station',at:{r:2,c:2},facing:'left'};}if(obstacle==='crew')ctx.state.crew.push(person('visitor',{r:2,c:2},null));if(obstacle==='fixture')ctx.state.fixtures.push({id:'ice',kind:'ice',at:{r:2,c:2},hp:1});expect(canMoveActor(ctx.state,'pair',{r:2,c:1})).toBe(false);expect(moveActor(ctx,'pair',{r:2,c:1})).toBe(false);expect(ctx.state.actors[0]!.at).toEqual({r:1,c:1});}});
 it('rejects swapped passengers, changed offsets and forged releases',()=>{module('tethers');const ctx=draft(tetherBoard());ctx.state.crew[0]!.at={r:1,c:2};expect(()=>parseCampaignState(ctx.state)).toThrow(/tether/);});
});
describe('kit carrying repair bots',()=>{
 it.each(['repair','bridge','gate'] as const)('%s can open first on a combined board; distinct permanent activations reload after every step',first=>{
  const l=repairBoard();l.geometry.inactiveCells.push({r:0,c:0},{r:1,c:4});
  l.pieces=l.pieces.filter(p=>!(p.at.r===0&&p.at.c===0)&&!(p.at.r===1&&p.at.c===4)&&!(p.at.r===2&&p.at.c===4));
  l.pieces.push({id:'key',kind:'cargo',cargoKind:'key',at:{r:2,c:4},destinationId:'lock',passengerIds:[]});
  l.fixtures=[{id:'bridge',kind:'bridge',at:{r:0,c:1},cells:[{r:0,c:0}],connectionIds:[],hits:0,active:false},{id:'gate',kind:'gate',at:{r:1,c:3},cells:[{r:1,c:4}],connectionIds:[],open:false},{id:'lock',kind:'lock',at:{r:2,c:4},gateId:'gate',keyId:'key'}];
  l.mechanics.push({id:'bridges',fixtureIds:['bridge']},{id:'keys',fixtureIds:['gate','lock']});
  l.goals=[{id:'restore',type:'restoreInfrastructure',eligible:{type:'ids',ids:['job','bridge','gate']}}];
  const ctx=draft(parseCampaignLevel(l));
  const open={repair:()=>{const m=module('repair');m.settle!(ctx);m.stepActor!(ctx,'bot');m.stepActor!(ctx,'bot');m.settle!(ctx);},bridge:()=>{const m=module('bridges');m.onMerge!(ctx,merge('bridge-one',[{r:0,c:1},{r:0,c:2},{r:0,c:3}]));m.onMerge!(ctx,merge('bridge-two',[{r:0,c:1},{r:0,c:2},{r:0,c:3}]));},gate:()=>{module('keys').beforeRefill!(ctx);}};
  expect(parseCampaignState(ctx.state)).toEqual(ctx.state);
  for(const id of [first,...(['repair','bridge','gate'] as const).filter(id=>id!==first)]){open[id]();refillPieces(ctx);expect(parseCampaignState(JSON.parse(JSON.stringify(ctx.state)))).toEqual(ctx.state);}
  expect(ctx.state.geometry.inactiveCells).toEqual([]);expect(ctx.state.goalProgress[0]!.completedIds).toEqual(['bridge','gate','job']);
 });
 it.each(['station','actor','crew','inactive'])('a collected kit cannot move its bot through a %s obstruction',obstacle=>{const m=module('repair'),ctx=draft(repairBoard());m.settle!(ctx);const at={r:3,c:1};if(obstacle==='station'){const p=ctx.state.pieces.findIndex(p=>p.at.r===at.r&&p.at.c===at.c);ctx.state.pieces[p]={id:'station',kind:'station',at,facing:'left'};}if(obstacle==='actor')ctx.state.actors.push({id:'other',kind:'pup',at,nurseryId:'nursery'});if(obstacle==='crew')ctx.state.crew.push(person('visitor',at,null));if(obstacle==='inactive')ctx.state.geometry.inactiveCells.push(at);m.stepActor!(ctx,'bot');expect(ctx.state.actors.find(a=>a.id==='bot')!.at).toEqual({r:3,c:0});expect(ctx.state.goalProgress[0]!.completedIds).toEqual([]);});
 it('collects its kit, follows its route and opens only the next adjacent broken cell',()=>{const m=module('repair'),ctx=draft(repairBoard());expect(m.settle!(ctx)).toBe(true);expect(ctx.state.actors[0]).toMatchObject({kitId:'kit'});expect(ctx.state.pieces.some(p=>p.id==='kit')).toBe(false);m.stepActor!(ctx,'bot');expect(ctx.state.actors[0]!.at).toEqual({r:3,c:1});expect(m.settle!(ctx)).toBe(false);m.stepActor!(ctx,'bot');expect(m.settle!(ctx)).toBe(true);expect(ctx.state.geometry.inactiveCells).toEqual([]);expect(ctx.state.goalProgress[0]!.completedIds).toEqual(['job']);expect(parseCampaignState(ctx.state)).toEqual(ctx.state);});
 it('waits without a kit and when its next route cell is blocked',()=>{const m=module('repair'),ctx=draft(repairBoard());m.stepActor!(ctx,'bot');expect(ctx.state.actors[0]!.at).toEqual({r:3,c:0});m.settle!(ctx);ctx.state.fixtures.push({id:'ice',kind:'ice',at:{r:3,c:1},hp:1});m.stepActor!(ctx,'bot');expect(ctx.state.actors[0]!.at).toEqual({r:3,c:0});expect(ctx.state.geometry.inactiveCells).toEqual([{r:3,c:3}]);});
 it('rejects duplicate jobs, active authored jobs and forged repair geometry',()=>{module('repair');const l=repairBoard();l.geometry.inactiveCells=[];expect(()=>parseCampaignLevel(l)).toThrow(/repair/);const ctx=draft(repairBoard());ctx.state.geometry.inactiveCells=[];expect(()=>parseCampaignState(ctx.state)).toThrow(/repair/);});
});
describe('simultaneous shuttle rendezvous',()=>{
 it('departs both exact occupied pods atomically and only once',()=>{const m=module('rendezvous'),ctx=draft(rendezvousBoard());m.finalize!(ctx);expect(ctx.state.pieces.filter(p=>p.kind==='pod')).toEqual([]);expect(ctx.state.crew.map(c=>c.status)).toEqual(['evacuated','evacuated']);expect(ctx.state.goalProgress[0]!.completedIds).toEqual(['first','second']);m.finalize!(ctx);expect(ctx.events.filter(e=>e.type==='rendezvous'&&e.phase==='departed')).toHaveLength(1);expect(parseCampaignState(ctx.state)).toEqual(ctx.state);});
 it('waits for both pads and rejects empty pods, exchanged passengers or an inactive pad',()=>{const m=module('rendezvous');for(const absent of ['away','empty','exchanged','inactive']){const ctx=draft(rendezvousBoard());if(absent==='away')ctx.state.pieces.find(p=>p.id==='pod-b')!.at={r:2,c:3};if(absent==='empty')(ctx.state.pieces.find(p=>p.id==='pod-b') as any).passengerIds=[];if(absent==='exchanged')ctx.state.crew[0]!.carrierId='pod-b';if(absent==='inactive')ctx.state.geometry.endpoints[1]!.active=false;m.finalize!(ctx);expect(ctx.state.crew.map(c=>c.status)).toEqual(['active','active']);expect(ctx.state.goalProgress[0]!.completedIds).toEqual([]);}});
 it('rejects a forged partial departure or moved staging pad',()=>{module('rendezvous');const ctx=draft(rendezvousBoard());ctx.state.crew[0]!.status='evacuated';ctx.state.crew[0]!.carrierId=null;(ctx.state.pieces.find(p=>p.id==='pod-a') as any).passengerIds=[];expect(()=>parseCampaignState(ctx.state)).toThrow(/rendezvous/);});
});
