import {expect,it} from 'vitest';
import {baseLevel,baseState,mergeSwap} from '../fixtures/base';
import {loadCampaignLevel} from '../../../src/campaign/engine/load';
import {transition} from '../../../src/campaign/engine/turn';
import {createContext} from '../../../src/campaign/engine/context';
import {resolveCrewSafety,tickNeeds} from '../../../src/campaign/engine/needs';
import {campaignModules} from '../../../src/campaign/mechanics/registry';
import {parseCampaignState,parseCampaignEvents,parseCampaignLevel} from '../../../src/campaign/schema';
import {crewGroupLabel} from '../../../src/render/campaign/mechanics';
function level(safe=false){const l=baseLevel();l.id=472;l.chapter=10;l.crew[0]!.at={r:3,c:0};if(safe){const p=l.pieces.find(p=>p.at.r===3&&p.at.c===0)!;if(p.kind==='tile')p.tier=4;}l.mechanics=[{id:'shelter',crewIds:['crew'],allowance:20}];return l;}
const module=()=>campaignModules.find(m=>m.id==='shelter');
it('first safe arrival activates once and emits the full allowance',()=>{const s=baseState(level(true));s.mechanics=[{id:'shelter',startedCrewIds:[]}];const c=createContext(s);module()?.settle?.(c);expect(s.crew[0]).toMatchObject({shelterMoves:20,shelterStarted:true});expect(s.mechanics).toEqual([{id:'shelter',startedCrewIds:['crew']}]);expect(c.events).toContainEqual(expect.objectContaining({type:'need',need:'shelter',before:null,after:20}));const count=c.events.length;module()?.settle?.(c);expect(c.events).toHaveLength(count);expect(parseCampaignEvents(c.events)).toEqual(c.events);});
it('initial safe load keeps 20, the next ordinary accepted move shows 19, and reload is identical',()=>{const s=loadCampaignLevel(level(true));expect(s.crew[0]!.shelterMoves).toBe(20);const r=transition(s,mergeSwap);expect(r.accepted).toBe(true);expect(r.state.crew[0]!.shelterMoves).toBe(19);expect(transition(parseCampaignState(JSON.parse(JSON.stringify(s))),mergeSwap)).toEqual(r);});
it('an ordinary activation transition retains 20 and only its newly started counter skips the tick',()=>{const l=level();l.crew[0]!.at={r:2,c:0};l.pieces=baseLevel([[1,2,1,3],[2,3,2,1],[3,4,3,2],[1,2,1,'S']]).pieces;const s=loadCampaignLevel(l),r=transition(s,{type:'swap',from:{r:1,c:1},to:{r:2,c:1}});expect(r.accepted).toBe(true);expect(r.state.crew[0]).toMatchObject({shelterMoves:20,shelterStarted:true,rescueMoves:null});expect(r.events.flatMap(e=>e.type==='need'&&e.need==='shelter'?[e.after]:[])).toEqual([20]);expect(parseCampaignState(JSON.parse(JSON.stringify(r.state)))).toEqual(r.state);});
it('both needs tick in danger; safety clears oxygen without restarting shelter across reload',()=>{const s=loadCampaignLevel(level(true)),p=s.pieces.find(p=>p.at.r===3&&p.at.c===0)!;s.crew[0]!.shelterMoves=6;if(p.kind==='tile')p.tier=1;const c=createContext(parseCampaignState(s));resolveCrewSafety(c);module()?.settle?.(c);tickNeeds(c);expect(c.state.crew[0]).toMatchObject({rescueMoves:19,shelterMoves:5});const saved=parseCampaignState(JSON.parse(JSON.stringify(c.state))),safe=saved.pieces.find(q=>q.id===p.id)!;if(safe.kind==='tile')safe.tier=4;const back=createContext(saved);resolveCrewSafety(back);module()?.settle?.(back);expect(back.state.crew[0]).toMatchObject({rescueMoves:null,shelterMoves:5});});
it('the displayed deadline is whichever independent need expires first',()=>{const c=baseState(level()).crew[0]!;c.rescueMoves=4;c.shelterMoves=9;expect(crewGroupLabel([c])).toBe('O\u2082 4');c.rescueMoves=12;expect(crewGroupLabel([c])).toBe('\u2302 9');});
it('station completion wins before a final unresolved tick and clears both counters',()=>{const s=loadCampaignLevel(level(true));s.crew[0]!.shelterMoves=2;s.crew[0]!.rescueMoves=1;const r=transition(s,{type:'swap',from:{r:3,c:3},to:{r:3,c:2}});expect(r.state.status).toBe('playing');expect(r.state.crew[0]!.shelterMoves).toBe(1);const final=transition(r.state,{type:'swap',from:{r:3,c:2},to:{r:3,c:1}});expect(final.state.status).toBe('won');expect(final.state.crew[0]).toMatchObject({rescueMoves:null,shelterMoves:null,status:'housed'});});
it('rejected moves and boosters do not tick an existing request',()=>{const s=loadCampaignLevel(level(true));const no=transition(s,{type:'swap',from:{r:0,c:0},to:{r:3,c:3}});expect(no.accepted).toBe(false);expect(no.state).toBe(s);const boost=transition(s,{type:'booster',kind:'demo',at:{r:0,c:2}});expect(boost.accepted).toBe(true);expect(boost.state.crew[0]!.shelterMoves).toBe(20);expect(boost.state.turn).toBe(0);});
it('ordinary unlabeled safe crew keep their established behavior',()=>{const l=level(true);l.mechanics=[];const s=loadCampaignLevel(l);expect(s.crew[0]).toMatchObject({rescueMoves:null,shelterMoves:null,shelterStarted:false});});
it('rejects lifetime ledger/flag contradictions rather than granting a second allowance',()=>{const s=loadCampaignLevel(level(true));s.mechanics=[{id:'shelter',startedCrewIds:[]}];expect(()=>parseCampaignState(s)).toThrow(/shelter/i);const other=loadCampaignLevel(level());other.mechanics=[{id:'shelter',startedCrewIds:['crew']}];expect(()=>parseCampaignState(other)).toThrow(/shelter/i);});
it('eligibility cannot refer to absent crew',()=>{const l=level();l.mechanics=[{id:'shelter',crewIds:['absent'],allowance:20}];expect(()=>parseCampaignLevel(l)).toThrow();});
import {getAuthoredLessonLevel} from '../../../src/campaign/lessons';
import {lessonTeachingActions} from '../../../src/campaign/content/lesson-solutions.dev';
import {shelterVisualState} from '../../../src/render/campaign/mechanics';
import {makeScene,applySceneEvents} from '../../../src/render/campaign/snapshot';
it.each([471,472,473,474,475])('lesson %s activates every labeled request and clears it through a genuine searched booster-free win',id=>{
 const l=getAuthoredLessonLevel(id)!,def=l.mechanics.find(m=>m.id==='shelter')!;let s=loadCampaignLevel(l);
 const started=new Set(s.crew.filter(c=>c.shelterStarted).map(c=>c.id));let running=false;
 for(const action of lessonTeachingActions[id]!){const saved=parseCampaignState(JSON.parse(JSON.stringify(s))),r=transition(s,action);expect(r.accepted).toBe(true);expect(transition(saved,action)).toEqual(r);expect(parseCampaignEvents(r.events)).toEqual(r.events);for(const c of r.state.crew)if(c.shelterStarted)started.add(c.id);if(r.state.crew.some(c=>c.status==='active'&&c.shelterMoves!==null))running=true;s=r.state;}
 expect(started.size).toBe(def.crewIds.length);expect(running).toBe(true);expect(s.status).toBe('won');expect(s.crew.every(c=>c.status==='housed'&&c.shelterMoves===null&&c.rescueMoves===null)).toBe(true);expect(parseCampaignState(JSON.parse(JSON.stringify(s)))).toEqual(s);
});
it('an old request ticks while another first safe arrival keeps twenty on the same move',()=>{const s=loadCampaignLevel(getAuthoredLessonLevel(474)!);const r=transition(s,lessonTeachingActions[474]![0]!);expect(r.state.crew.map(c=>c.shelterMoves)).toEqual([19,20]);expect(r.state.crew.map(c=>c.rescueMoves)).toEqual([null,null]);});
it('safe shelter expiration loses without revoking the lifetime allowance',()=>{const s=loadCampaignLevel(level(true));s.crew[0]!.shelterMoves=1;const r=transition(s,mergeSwap);expect(r.state.status).toBe('lost');expect(r.state.crew[0]).toMatchObject({status:'lost',shelterStarted:true,shelterMoves:0});expect(parseCampaignState(r.state)).toEqual(r.state);});
it('renderer preserves eligible identity and projects request events while the earlier clock drives urgency',()=>{const s=loadCampaignLevel(getAuthoredLessonLevel(474)!),scene=makeScene(s),r=transition(s,lessonTeachingActions[474]![0]!);expect(scene.shelterCrewIds).toEqual(['crew-0','crew-1']);const projected=applySceneEvents(scene,r.events);expect(projected.crew).toEqual(makeScene(r.state).crew);const c=structuredClone(s.crew[0]!);expect(shelterVisualState(c)).toBe('calm');c.rescueMoves=3;expect(shelterVisualState(c)).toBe('urgent');c.status='housed';c.rescueMoves=null;c.shelterMoves=null;expect(shelterVisualState(c)).toBe('complete');c.status='active';c.shelterStarted=false;expect(shelterVisualState(c)).toBe('waiting');});
