import {expect,it} from 'vitest';
import {loadCampaignLevel} from '../../../src/campaign/engine/load';
import {transition} from '../../../src/campaign/engine/turn';
import {parseCampaignState} from '../../../src/campaign/schema';
import {harvestCrateLevel,waitingMerge,openingMerge} from '../fixtures/harvest-crate';

it('live harvest stays above a crate then descends to its exit with one delivery credit',()=>{
 const initial=loadCampaignLevel(harvestCrateLevel('cargo'));
 expect(initial.pieces.find(p=>p.id==='harvest-0')?.at).toEqual({r:1,c:2});
 const waiting=transition(initial,waitingMerge);
 expect(waiting.accepted).toBe(true);
 expect(waiting.events.some(e=>e.type==='merge')).toBe(true);
 expect(waiting.state.pieces.find(p=>p.id==='harvest-0')).toEqual(initial.pieces.find(p=>p.id==='harvest-0'));
 expect(waiting.state.fixtures.find(f=>f.id==='crop-crate')?.kind).toBe('crate');
 expect(waiting.events.some(e=>(e.type==='move'&&e.entityId==='harvest-0')||(e.type==='remove'&&e.piece.id==='harvest-0'))).toBe(false);
 expect(waiting.state.mechanics.find(m=>m.id==='exits')?.departedIds).toEqual([]);
 expect(waiting.state.goalProgress.every(g=>g.completedIds.length===0)).toBe(true);
 const restored=parseCampaignState(JSON.parse(JSON.stringify(waiting.state)));
 const opened=transition(restored,openingMerge);
 expect(opened.accepted).toBe(true);
 expect(opened).toEqual(transition(waiting.state,openingMerge));
 const removed=opened.events.findIndex(e=>e.type==='fixture'&&e.fixtureId==='crop-crate'&&e.after===null);
 const descent=opened.events.findIndex(e=>e.type==='move'&&e.entityId==='harvest-0');
 const departure=opened.events.findIndex(e=>e.type==='remove'&&e.piece.id==='harvest-0'&&e.reason==='departure');
 expect(removed).toBeGreaterThanOrEqual(0);
 expect(descent).toBeGreaterThan(removed);
 expect(departure).toBeGreaterThan(descent);
 expect(opened.events[descent]).toMatchObject({type:'move',entityId:'harvest-0',from:{r:1,c:2},to:{r:3,c:2}});
 expect(opened.events.filter(e=>e.type==='remove'&&e.piece.id==='harvest-0'&&e.reason==='departure')).toHaveLength(1);
 expect(opened.state.pieces.some(p=>p.id==='harvest-0')).toBe(false);
 expect(opened.state.mechanics.find(m=>m.id==='exits')?.departedIds).toEqual(['harvest-0']);
 expect(opened.state.mechanics.find(m=>m.id==='crates')?.openedIds).toEqual(['crop-crate']);
 expect(opened.state.goalProgress).toEqual([{goalId:'supplies',completedIds:['crop-crate']},{goalId:'harvest',completedIds:['harvest-0']}]);
 expect(opened.state.status).toBe('won');
 const delivered=parseCampaignState(JSON.parse(JSON.stringify(opened.state)));
 const repeated=transition(delivered,openingMerge);
 expect(repeated.accepted).toBe(false);
 expect(repeated.events).toEqual([]);
 expect(repeated.state).toEqual(delivered);
});
